import fs from 'node:fs';import assert from 'node:assert/strict';import * as THREE from 'three';
import {GLTFLoader} from '../3d/vendor/loaders/GLTFLoader.js';
import {createHoConRua,HO_CON_RUA} from '../3d/ho-con-rua.js';
const paths=JSON.parse(fs.readFileSync(new URL('../3d/ho-con-rua-paths.json',import.meta.url)));
const project=(lon,lat)=>[(lon-106.65)*111320*Math.cos(10.81*Math.PI/180),-(lat-10.81)*111320];
const scene=new THREE.Scene(),m=createHoConRua({scene,project,paths});await m.ready;
assert.equal(m.state.piers,5);assert.equal(m.state.crownRibs,25);assert(m.state.pathsLoaded);
assert.equal(m.group.parent,scene);assert.deepEqual(m.group.position.toArray(),[...project(HO_CON_RUA.lon,HO_CON_RUA.lat).slice(0,1),0,project(HO_CON_RUA.lon,HO_CON_RUA.lat)[1]]);
const box=new THREE.Box3().setFromObject(m.group);assert(Math.abs(box.max.y-34)<0.05);
m.group.traverse(o=>{if(o.isMesh){assert(o.geometry.attributes.position.array.every(Number.isFinite),o.name);assert(o.geometry.attributes.normal.array.every(Number.isFinite),o.name);}});
const bytes=fs.readFileSync(new URL('../3d/assets/tiles/2_1.glb',import.meta.url));const {scene:tile}=await new GLTFLoader().parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'');
const counts=()=>Object.fromEntries(tile.children.filter(o=>o.isMesh).map(o=>[o.name,(o.geometry.index?.count??o.geometry.attributes.position.count)/3]));
const before=counts(),cut=m.replaceGeneric(tile),after=counts();assert(cut>=576,`Remove generic lake bridges: ${cut}`);
for(const key of ['building','building-tagged','water','major','street','green'])assert.equal(before[key],after[key],`${key} preserved`);
assert.equal(m.replaceGeneric(tile),0,'Replacement is idempotent');
const overviewBytes=fs.readFileSync(new URL('../3d/assets/overview.glb',import.meta.url));
const {scene:overview}=await new GLTFLoader().parseAsync(overviewBytes.buffer.slice(overviewBytes.byteOffset,overviewBytes.byteOffset+overviewBytes.byteLength),'');
const lineCut=m.replaceGeneric(overview);assert(lineCut>0,'Old overview footbridge lines removed');
assert.equal(m.replaceGeneric(overview),0);
let disposed=0;m.group.traverse(o=>{if(o.isMesh)o.geometry.addEventListener('dispose',()=>disposed++);});const meshes=m.group.children.filter(o=>o.isMesh).length+1;
m.dispose();m.dispose();assert.equal(m.group.parent,null);assert.equal(disposed,meshes);
console.log(JSON.stringify({name:m.state.name,center:[HO_CON_RUA.lon,HO_CON_RUA.lat],height:box.max.y,triangles:m.state.triangles,removedGenericTriangles:cut,removedOverviewSegments:lineCut,preservedRoads:true,disposal:'passed'}));
