import assert from 'node:assert/strict';import fs from 'node:fs';import * as THREE from 'three';import {GLTFLoader} from '../3d/vendor/loaders/GLTFLoader.js';import {createSevenKhoCity,SEVEN_KHO_SITE} from '../3d/seven-kho-city.js';
const site=JSON.parse(fs.readFileSync(new URL('../3d/seven-kho-site.json',import.meta.url)));assert.equal(site.lon,SEVEN_KHO_SITE.lon);assert.equal(site.lat,SEVEN_KHO_SITE.lat);assert.equal(site.yaw,SEVEN_KHO_SITE.yaw);
const project=(lon,lat)=>[(lon-106.65)*111320*Math.cos(10.81*Math.PI/180),-(lat-10.81)*111320];const scene=new THREE.Scene(),m=createSevenKhoCity({scene,project}),camera=new THREE.PerspectiveCamera();assert.equal(m.state.lod,'proxy');camera.position.copy(m.view.eye);m.update(camera);assert.equal(m.state.lod,'detail');
const detail=m.group.children.find(o=>o.name==='seven-kho');assert.ok(detail);let maxZ=-Infinity;detail.traverse(o=>{if(!o.isMesh)return;for(const v of o.geometry.attributes.position.array)assert.ok(Number.isFinite(v));});
// Check visible restaurant vertices below 3 m (tree canopy may overhang) against the mapped main carriageway.
const distance=(p,a,b)=>{const d=b.clone().sub(a),t=Math.max(0,Math.min(1,p.clone().sub(a).dot(d)/d.lengthSq()));return p.distanceTo(a.clone().addScaledVector(d,t));};
m.group.updateMatrixWorld(true);let roadClearance=Infinity,alleyClearance=Infinity;const alley=site.roadContext.find(r=>r.id===35114554).coords.map(p=>new THREE.Vector2(...project(...p)));
const segments=site.roadContext.filter(r=>r.id!==35114554).flatMap(r=>r.coords.slice(1).map((c,i)=>[new THREE.Vector2(...project(...r.coords[i])),new THREE.Vector2(...project(...c))]));
m.group.traverse(o=>{if(!o.isMesh)return;let p=o;while(p){if(!p.visible)return;p=p.parent;}const attr=o.geometry.attributes.position;for(let i=0;i<attr.count;i++){const v=new THREE.Vector3().fromBufferAttribute(attr,i).applyMatrix4(o.matrixWorld),p=new THREE.Vector2(v.x,v.z);if(v.y>3)continue;for(let j=1;j<alley.length;j++)alleyClearance=Math.min(alleyClearance,distance(p,alley[j-1],alley[j])-1.75);for(const [a,b]of segments)roadClearance=Math.min(roadClearance,distance(p,a,b)-3.2);}});assert.ok(alleyClearance>0,`alley overlap ${alleyClearance}`);assert.ok(roadClearance>0,`road overlap ${roadClearance}`);
const bytes=fs.readFileSync(new URL('../3d/assets/tiles/1_2.glb',import.meta.url));const tile=await new GLTFLoader().parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'');let before=0;tile.scene.traverse(o=>before+=o.geometry?.attributes.position.count??0);assert.equal(m.replaceGeneric(tile.scene),0);let after=0;tile.scene.traverse(o=>after+=o.geometry?.attributes.position.count??0);assert.equal(before,after);
camera.position.set(0,10000,0);m.update(camera);assert.equal(m.state.lod,'proxy');assert.ok(!m.group.children.includes(detail));m.dispose();m.dispose();assert.equal(m.group.parent,null);
console.log(JSON.stringify({placement:[site.lon,site.lat],footprint:site.footprintStatus,roadClearanceMetres:roadClearance,alleyClearanceMetres:alleyClearance,lod:'passed',neighborPreservation:'passed',finiteGeometry:'passed',disposal:'passed'}));
